---

- name: Ensure BioLighthouse and software directories exist
  file:
    path: "{{ base_path }}/{{ item }}"
    state: directory
    mode: 0777
  with_items:
    - .biolighthouse
    - .biolighthouse/software
    - .biolighthouse/software/conda

- name: Get the Mininconda3 installer
  get_url:
    url: https://repo.anaconda.com/archive/Anaconda2-2019.10-Linux-x86_64.sh
    dest: "{{ base_path }}/.biolighthouse/software/conda_install.sh"
    timeout: 1800
    mode: 0777
  # when: minIT is not defined

# - name: Ensure umask 007
#   lineinfile:
#     path: "{{ ansible_env.HOME }}/.bashrc"
#     line: "umask 007"

# - name: Get the Miniconda3 installer
#   get_url:
#     url: https://github.com/Archiconda/build-tools/releases/download/0.2.3/Archiconda3-0.2.3-Linux-aarch64.sh
#     dest: "{{ base_path }}/.biolighthouse/software/conda_install.sh"
#     timeout: 1800
#   when: minIT|bool == True

- name: Run the Anaconda3 installer
  shell: "bash {{ base_path }}/.biolighthouse/software/conda_install.sh -u -b -p {{ base_path }}/.biolighthouse/software/conda"
  args:
    creates: "{{ base_path }}/.biolighthouse/software/conda/bin/conda"
  notify: Remove installer

- name: Initialize conda shell
  command: "{{ base_path }}/.biolighthouse/software/conda/bin/conda init bash"
  # when: minIT is not defined
